### ISSUE TITLE
Missing .gitignore

### ISSUE THREAD

**Issue by mertssmnoglu** [busenurcetin/nodejs#1]
There is no .gitignore file in this repository. It can be basically added with github>Create file>.gitignore
Then you should choose "NodeJS" template and commit it.

**Comment by mertssmnoglu** [comment]
Ds store files are useless and it should be ignored from source control mechanism.

**Comment by busenurcetin** [comment]
thank you so much @mertssmnoglu I added it, better now :)

**Comment by busenurcetin** [comment]
Closed this issue after fixing problem (adding .gitignore)
